New commands for ddiflow
New command: feature reviewstart
New command: feature reviewfinish
Modified command: feature start

diff --git a/git-hf-feature b/git-hf-feature
--- a/git-hf-feature
+++ b/git-hf-feature
@@ -43,7 +43,6 @@
 require_git_repo
 require_hubflow_initialized
 hubflow_load_settings
-ddiflow_load_settings
 PREFIX=$(git config --get hubflow.prefix.feature)
 
 usage() {
@@ -58,6 +57,8 @@ usage() {
 	echo "       git hf feature pull [-r] [<remote> [<name>]]"
 	echo "       git hf feature push [<remote> [<name>]]"
 	echo "       git hf feature cancel [-f] <name>"
+	echo "       git hf feature reviewstart [<name>]"
+	echo "       git hf feature reviewfinish [<name>]"
 }
 
 cmd_default() {
@@ -559,3 +560,70 @@ cmd_cancel() {
 	fi
 	echo
 }
+
+cmd_reviewstart() {
+	parse_args "$@"
+	expand_nameprefix_arg_or_current
+
+	# sanity checks
+	require_branch "$BRANCH"
+	require_clean_working_tree
+	require_remote_available
+
+	if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
+		require_branches_equal "$BRANCH" "$ORIGIN/$BRANCH"
+	fi
+
+  if ! ddiflow_github_pullrequest_start "$BRANCH"; then
+    warn "Could not create a pull request"
+    exit 1
+  fi
+
+  issue=$(ddiflow_extract_issue $BRANCH)
+  issuemsg="- There was an error updating issue $issue, so you should update it manually"
+  if [ -n "$issue" ]; then
+    ddiflow_issue_transition "$issue" 'to code review'
+    if [ $? -eq 0 ]; then
+      issuemsg="- Updated issue $issue"
+    fi
+  fi
+
+	echo
+	echo "Summary of actions:"
+  echo "- Created a pull request for branch $BRANCH"
+  echo "$issuemsg"
+}
+
+cmd_rs() {
+	# Alias for code review
+	cmd_reviewstart "$@"
+}
+
+cmd_reviewfinish() {
+	parse_args "$@"
+	expand_nameprefix_arg_or_current
+
+	# sanity checks
+	require_branch "$BRANCH"
+	require_clean_working_tree
+	require_remote_available
+
+	if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
+		require_branches_equal "$BRANCH" "$ORIGIN/$BRANCH"
+	fi
+
+  if ! ddiflow_github_pullrequest_finish "$BRANCH"; then
+    warn "Could not close the pull request"
+    exit 1
+  fi
+
+	echo
+	echo "Summary of actions:"
+  echo "- Closed the pull request for branch $BRANCH"
+}
+
+cmd_rf() {
+	# Alias for code review
+	cmd_reviewfinish "$@"
+}
+
